copyright = "© 2021-2022 Daniel F. Dickinson"
homepage = "https://github.com/danielfdickinson/image-handling-mod-hugo-dfd/"
description = "Hugo module for handling images and image-related functionality for themes"
enableGitInfo = true
defaultContentLanguage = "en"

# See https://gohugo.io/content-management/multilingual/
# and https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/
[languages]
  [languages.en]
    languageName = ":en:"
    languageAltTitle = "English"
    title = "DFD Image Handling Hugo Module"
    weight = 1

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/about/"
  email = "dfdpublic@wildtechgarden.ca"

  [[author.authors]]
    name = "Daniel F. Dickinson"
    homepage = "https://www.danielfdickinson.ca/about/"
    email = "dfdpublic@wildtechgarden.ca"

[module]
  [[module.imports]]
    path = "github.com/danielfdickinson/link-handling-mod-hugo-dfd"
