---
name: build-and-verify
on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - 'feature**'
      - main
      - 'staging**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode'
      - 'scripts'
jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        hugo: ["0.80.0", "0.88.1", "latest"]
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/build-audit-action-hugo-dfd@v0.2.0
        with:
          hugo-version: ${{ matrix.hugo }}
          upload-site-as: unminified-site-${{ matrix.hugo }}
          use-lfs: true
          source-directory: exampleSite
  validate-unminified-html:
    needs: build-unminified-site
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        hugo: ["0.80.0", "0.88.1", "latest"]
    steps:
      - uses: actions/checkout@v2
      - name: "Validate exampleSite HTML"
        uses: danielfdickinson/validate-html-action-hugo-dfd@v0.2.0-beta.1
        with:
          download-site-as: unminified-site-${{ matrix.hugo }}
  check-links:
    needs: build-unminified-site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Check internal links"
        uses: danielfdickinson/link-check-action-hugo-dfd@v0.2.0-beta.1
        with:
          canonical-root: https://example.com/
          download-site-as: unminified-site-latest
          entry-point: index.html
          upload-logs-as: check-links-failure
          upload-logs-retention: 3
